
package batallanaval;

import java.awt.MouseInfo;
import java.awt.Point;


public class Tablero extends javax.swing.JFrame {
int varX = 80;
int varY = 60;

    public Tablero() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barco2 = new javax.swing.JLabel();
        Barco1 = new javax.swing.JLabel();
        barco6 = new javax.swing.JLabel();
        barco5 = new javax.swing.JLabel();
        barco3 = new javax.swing.JLabel();
        barco4 = new javax.swing.JLabel();
        barco8 = new javax.swing.JLabel();
        barco7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtY = new javax.swing.JTextField();
        txtX = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        barco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco1.png"))); // NOI18N
        barco2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barco2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barco2MouseDragged(evt);
            }
        });
        jPanel1.add(barco2);
        barco2.setBounds(50, 90, 144, 63);

        Barco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco2.png"))); // NOI18N
        Barco1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Barco1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barco1MouseDragged(evt);
            }
        });
        jPanel1.add(Barco1);
        Barco1.setBounds(40, 20, 116, 62);

        barco6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco3.png"))); // NOI18N
        barco6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barco6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barco6MouseDragged(evt);
            }
        });
        jPanel1.add(barco6);
        barco6.setBounds(50, 480, 104, 87);

        barco5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco4.png"))); // NOI18N
        barco5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barco5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barco5MouseDragged(evt);
            }
        });
        jPanel1.add(barco5);
        barco5.setBounds(50, 380, 87, 70);

        barco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco5.png"))); // NOI18N
        barco3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barco3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barco3MouseDragged(evt);
            }
        });
        jPanel1.add(barco3);
        barco3.setBounds(60, 200, 87, 50);

        barco4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco6.png"))); // NOI18N
        barco4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barco4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barco4MouseDragged(evt);
            }
        });
        jPanel1.add(barco4);
        barco4.setBounds(30, 280, 137, 65);

        barco8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco8.png"))); // NOI18N
        barco8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barco8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barco8MouseDragged(evt);
            }
        });
        jPanel1.add(barco8);
        barco8.setBounds(60, 660, 102, 70);

        barco7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco7.png"))); // NOI18N
        barco7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barco7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barco7MouseDragged(evt);
            }
        });
        jPanel1.add(barco7);
        barco7.setBounds(20, 580, 224, 65);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agua.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 150, 725, 590);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usuario Activo:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 20, 140, 22);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(490, 20, 300, 30);
        jPanel1.add(txtY);
        txtY.setBounds(1050, 0, 70, 30);
        jPanel1.add(txtX);
        txtX.setBounds(960, 0, 70, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Barco1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barco1MouseDragged
        Point punto = MouseInfo.getPointerInfo().getLocation();
        this.Barco1.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
        this.txtY.setText(String.valueOf(punto.y));        
        
    }//GEN-LAST:event_Barco1MouseDragged

    private void barco2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barco2MouseDragged
        Point punto = MouseInfo.getPointerInfo().getLocation();
        this.barco2.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
    
        this.txtY.setText(String.valueOf(punto.y));   
    }//GEN-LAST:event_barco2MouseDragged

    private void barco3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barco3MouseDragged
        // TODO add your handling code here:
         Point punto = MouseInfo.getPointerInfo().getLocation();
        this.barco3.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
    
        this.txtY.setText(String.valueOf(punto.y));   
    }//GEN-LAST:event_barco3MouseDragged

    private void barco4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barco4MouseDragged
        // TODO add your handling code here:
      Point punto = MouseInfo.getPointerInfo().getLocation();
        this.barco4.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
    
        this.txtY.setText(String.valueOf(punto.y));    
    }//GEN-LAST:event_barco4MouseDragged

    private void barco5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barco5MouseDragged
Point punto = MouseInfo.getPointerInfo().getLocation();
        this.barco5.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
    
        this.txtY.setText(String.valueOf(punto.y));  
    }//GEN-LAST:event_barco5MouseDragged

    private void barco6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barco6MouseDragged
 Point punto = MouseInfo.getPointerInfo().getLocation();
        this.barco6.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
    
        this.txtY.setText(String.valueOf(punto.y));       }//GEN-LAST:event_barco6MouseDragged

    private void barco7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barco7MouseDragged
Point punto = MouseInfo.getPointerInfo().getLocation();
        this.barco7.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
    
        this.txtY.setText(String.valueOf(punto.y));       }//GEN-LAST:event_barco7MouseDragged

    private void barco8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barco8MouseDragged
            Point punto = MouseInfo.getPointerInfo().getLocation();
        this.barco8.setLocation(punto.x-varX, punto.y-varY);
        
        this.txtX.setText(String.valueOf(punto.x));
    
        this.txtY.setText(String.valueOf(punto.y));       }//GEN-LAST:event_barco8MouseDragged
     
    
    /** private void barco3MouseDragged(java.awt.event.MouseEvent evt) {                                    
       
    }                                   
  
     *    private void barco4MouseDragged(java.awt.event.MouseEvent evt) {                                    
         
    }                                   
    private void barco5MouseDragged(java.awt.event.MouseEvent evt) {                                    
         
    }                                   
    private void barco6MouseDragged(java.awt.event.MouseEvent evt) {                                    
       
    }                                   
 private void barco7MouseDragged(java.awt.event.MouseEvent evt) {                                    
        
    }                                   
 private void barco8MouseDragged(java.awt.event.MouseEvent evt) {                                    
      
    }                                   

     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barco1;
    private javax.swing.JLabel barco2;
    private javax.swing.JLabel barco3;
    private javax.swing.JLabel barco4;
    private javax.swing.JLabel barco5;
    private javax.swing.JLabel barco6;
    private javax.swing.JLabel barco7;
    private javax.swing.JLabel barco8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    // End of variables declaration//GEN-END:variables
}
